font_family Maple Mono NF
font_size 11

confirm_os_window_close 0
enable_audio_bell no
cursor_shape block
mouse_hide_wait -1
background_opacity 0.85
shell /bin/bash

foreground #c8c8c8
background #1e1e1e
selection_foreground #000000
selection_background #D3ECCA
url_color #a6da95
cursor #D3ECCA
active_border_color #a6da95
inactive_border_color #444444
tab_bar_background #1e1e1e
active_tab_foreground #000000
active_tab_background #D3ECCA
inactive_tab_foreground #c8c8c8
inactive_tab_background #2a2a2a

color0 #1e1e1e
color1 #ed8796
color2 #a6da95
color3 #eed49f
color4 #8aadf4
color5 #c6a0f6
color6 #8bd5ca
color7 #b8c0e0
color8 #6e738d
color9 #ed8796
color10 #a6da95
color11 #eed49f
color12 #8aadf4
color13 #c6a0f6
color14 #8bd5ca
color15 #cad3f5
